### ISSUE TITLE
Rare issue in verification system

### ISSUE THREAD

**Issue by ShubhamBhut** [NIT-KKR-Student-Support-System/Project-Hyperlink#27]
If the immediate next message after OTP request is from anyone else, the bot shuts off the verification process.
[reference](https://discord.com/channels/904633974306005033/904637373445439488/1065217916590633010)

**Comment by GetPsyched** [comment]
I don't understand the reference. The bot clearly responded

**Comment by GetPsyched** [comment]
Fixed
